### ISSUE TITLE
SaaS Template for Wasp ^0.11.*

### ISSUE THREAD

**Issue by RaigaK** [wasp-lang/SaaS-Template-GPT#5]
it is supported ? 
Im getting errors when i try to use it, was working fine with 0.10.x

`[Server]  src/ext-src/queries.ts(5,51): error TS2344: Type 'unknown' does not satisfy the constraint 'Payload'.
[Server]  [nodemon] app crashed - waiting for file changes before starting...`

Getting some errors on {formErrors.instructions && formErrors.instructions.message} on GptPage.tsx too

**Comment by RaigaK** [comment]
I believe i created the template with the old template so below is how i fixed it
Had to take a look at starters repo for fix. [030ad1df14caed9e921d0f956013d09099c733af](https://github.com/wasp-lang/starters/commit/030ad1df14caed9e921d0f956013d09099c733af)

and probably {formErrors.instructions && formErrors.instructions.message} is on my part. so im closing this for now
